### ISSUE TITLE
Allow label renaming

### ISSUE THREAD

**Issue by larsks** [micnncim/action-label-syncer#59]
If I have a label `bug` and I would like it to be `type: bug`, I wish I could do something like this:

```
- name: "type: bug"
  alias: "bug"
```

And then label-syncer would:

- Create a new label `type: bug` if no label named either `type: bug` or `bug` exists, or
- Rename an existing label `bug` to be `type: bug`

This would make it much easier to make a set of existing repositories consistent.

**Comment by joeyparrish** [comment]
I found it necessary to extend this original idea a bit.  To support a single config to get multiple, divergent repos using the same labels, I need support for multiple aliases for some:

```yaml
- name: "Type: bug"
  aliases:
    - bug
    - defect
  description: Something isn't working
  color: d73a4a
```

I think we should support both syntaxes (single alias and multiple).  But having support for either a string or an array of them in the parser seems to require two different field names (`alias` as a string, and `aliases` for an array of strings).
