### ISSUE TITLE
Labels with long descriptions fail to create silently.

### ISSUE THREAD

**Issue by jambonrose** [micnncim/action-label-syncer#64]
Thank you for building this action. It's been really great to work with.

There's a small bug due to Github limits. As described, if I create a label with a long description, the action will inform me that everything is working, but Github will not create the label.

Below is an example label and output.

```yaml
- name: "Status: Author Working"
  description: >
      The author is working. If others may still review, this label may be used
      at same time as the "Ready for Review" label.
  color: FFBF00
```

I've modified the output below to improve readability.

```
label: {
	Name:Status: Author Working
	Description:
		The author is working. If others may still review, this label may
		be used at same time as the "Ready for Review" label.
 	Color:FFBF00
 }
 created on: jambonrose/architecture.andrewsforge.com
 ```
 
When I check the list of labels, the label is missing. If I shorten the description to be equal to or less than 100 characters, then the label is created successfully.

I propose that the action explicitly warns people if the label creation step has failed. Including the reason it failed would also be quite helpful.

**Comment by thclark** [comment]
This is essentially a validation error - github is rejecting the labels which don't neet github's schema, but presumably responding with a 200 status anyhow.

Effectively the same issue occurs with incorrect color codes too... for example...
```yml
- name: duplicate
  description: This issue or pull request already exists
  color: cfd3d7
- name: epic
  description: Contains links to a collection of issues
  color: #cc00ff
```
...shows correct creation of both labels in the log, but the `epic` label doesn't appear (because we're not supposed to have the colour code).

It'd be worth using a yaml schema to actually validate the whole label before sending it to github, that'd help to draw out where the actual errors are.
