### ISSUE TITLE
Import statements

### ISSUE THREAD

**Issue by joeyparrish** [micnncim/action-label-syncer#69]
An import statement would enhance our ability to share configs across repos. Common fields needed by all repos (such as Type: bug) could be placed in a common config file. Then, each repo has its own config file with its unique labels, and the common ones get imported. For example:

```yaml
# common.yaml
- name: "Type: bug"
  description: Something isn't working
  color: d73a4a
```

```yaml
# repo1.yaml
- import: common.yaml

- name: "Platform: iOS"
  description: Issues specific to iOS
  color: d73a4a
```
