### ISSUE TITLE
trim whitespaces from elements of repository list

### ISSUE THREAD

**Issue by SebastianOpriel** [micnncim/action-label-syncer#75]
If a white space is accidentally added to a repository name in a repository config list, this repository is not synced and also no error is shown. As URLs do not end with white spaces, these could be trimmed automatically to avoid mistakes. In belows case, REPO2 would not be synced cause of the white space at its end.

```yml
jobs:
  sync_labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: micnncim/action-label-syncer@v1.3.0
        with:
          manifest: .github/sync_labels.yml
          prune: false
          repository: |
            ORG/REPO1
            ORG/REPO2 
            ORG/REPO3
          token: ${{ secrets.PAT}}
```
