### ISSUE TITLE
Label sync job completes, but does not update or change labels

### ISSUE THREAD

**Issue by mrz1836** [micnncim/action-label-syncer#79]
Hi! I have used this workflow in many repositories, private and public and it was working great. However, in my most recent repository, the label sync is not working. The job completes successfully, no error, and no labels affected.

Example running the workflow:
<img width="1432" alt="Screenshot 2023-04-11 at 8 11 47 AM" src="https://user-images.githubusercontent.com/3743002/231159081-7660eeda-4bdb-48f0-990b-935597489882.png">

Example of old labels:
<img width="547" alt="Screenshot 2023-04-11 at 8 12 00 AM" src="https://user-images.githubusercontent.com/3743002/231159120-10467b73-5170-42cb-a64b-d17525216807.png">

Here is my .labels file which triggers the build:

<img width="677" alt="Screenshot 2023-04-11 at 8 12 10 AM" src="https://user-images.githubusercontent.com/3743002/231159189-53a867bc-b77c-4c73-8d54-9f860568f1ae.png">

Any ideas why its failing? Did GitHub change something?

**Comment by mrz1836** [comment]
Here is also the workflow

```
# Workflow: https://github.com/micnncim/action-label-syncer
# Export your labels: https://github.com/micnncim/label-exporter
name: sync-labels
on:
  push:
    branches:
      - master
    paths:
      - .github/labels.yml
jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: micnncim/action-label-syncer@v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          manifest: .github/labels.yml
```
